# Surrogate Factory — UCFatigue
## Chapter 3. Data Cleaning
Objectives:
- Fill `Frontal gust` NaN with 0 (no frontal gust event → zero load).
- Fill `Xcg(%CMA)` NaN with column median.
- Remove `Type_segment` values with leading spaces (data quality).

### 0. Workflow initialisation

In [1]:
from IPython.display import display, HTML, JSON
from surrogate_factory.workflow import Workflow

workflow = Workflow("pipeline_config.yaml")
workflow.resume()

2026-06-25 12:24:21 - SurrogateFactoryLogs - INFO - Initializing Workflow...

2026-06-25 12:24:21 - SurrogateFactoryLogs - INFO - Setting up Workflow folders and paths...

2026-06-25 12:24:21 - SurrogateFactoryLogs - INFO - Changing working directory to Data folder: /Users/martaarnabatmartin/Desktop/Pipelines/UCFatigue/pipeline/data

2026-06-25 12:24:21 - SurrogateFactoryLogs - INFO - Loading default metadata schema...

2026-06-25 12:24:21 - SurrogateFactoryLogs - INFO - Tracker requested: 'mlflow'

2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - Setting up MLflow tracking environment...

Setting tracking uri: file:///Users/martaarnabatmartin/Desktop/Pipelines/UCFatigue/pipeline/mlruns
2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - Adding methods to Catalog from configuration.

2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - Workflow initialization completed successfully.

2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - Resuming workflow job: 'UCFATIGUE_1'

2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - Workflow data loaded successfully.

2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - Workflow metadata successfully loaded for resume.

### 3. Data Cleansing

In [2]:
workflow.import_metadata(stage_name="SF_3_Data_Cleansing")

2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - Importing metadata for stage: 'SF_3_Data_Cleansing'

2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - Updating metadata for stage 'Data_Cleansing' in memory.

VBox(children=(HTML(value='<h1>Form</h1>'), VBox(children=(Accordion(children=(VBox(children=(Textarea(value='…

In [3]:
outputFilename = workflow.config['job_name'] + '_raw_dataset.csv'
Dataset = workflow.load_data(outputFilename)
Dataset.describe()

2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - Loading data from '/Users/martaarnabatmartin/Desktop/Pipelines/UCFatigue/pipeline/data/UCFATIGUE_1_raw_dataset.csv' (Format: csv)

2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - Successfully loaded data shape: (869, 29)

,SSE,Seg,FLAP,Altitude,TAS,Time,Distance,Pressure,THRUST,Mass,...,1g,Vertical maneuver,Vertical gust,Turn,Frontal gust,n0,Giro,Xcg(%CMA),q,gamma
count,869.0,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000,361.000000,465.000000,869.000000,...,869.000000,869.000000,869.000000,869.000000,129.000000,869.000000,869.000000,821.000000,869.000000,869.000000
mean,2110017.0,42.211738,2.218642,9294.634062,190.871043,5.671646,18.736686,3.170886,7.148645,18874.777906,...,53.622806,19.137703,0.649379,6.362113,3.237240,1.939056,1.995853,19.463934,4510.245290,-0.266692
std,0.0,28.767722,5.369574,7701.901926,48.867640,24.658221,90.687607,1.906679,6.800328,1324.688731,...,8.296235,2.454225,0.168054,0.641480,0.196348,0.077678,1.532889,4.206660,1845.316550,4.573436
min,2110017.0,7.000000,0.000000,18.000000,101.000000,0.100000,0.200000,0.130000,-3.250000,14125.000000,...,31.561000,12.031000,0.346600,4.122000,2.542000,1.730000,0.662000,14.600000,1652.386607,-39.450765
25%,2110017.0,18.000000,0.000000,2000.000000,144.000000,0.490000,1.600000,1.430000,-0.060000,17761.000000,...,47.364000,17.185000,0.509700,6.010000,3.182000,1.900000,1.299000,16.400000,2881.202593,-4.704237
50%,2110017.0,35.000000,0.000000,8000.000000,197.571208,0.930000,2.500000,3.440000,7.320000,18905.000000,...,51.778000,18.893000,0.575000,6.382000,3.236000,1.940000,1.587000,18.500000,3579.988216,0.000000
75%,2110017.0,60.000000,0.000000,15000.000000,230.000000,3.000000,9.600000,4.980000,11.970000,19991.000000,...,61.558000,21.394000,0.806000,6.830000,3.350000,1.980000,1.874000,20.580000,6375.463109,2.944179
max,2110017.0,122.000000,23.000000,26000.000000,302.000000,623.000000,2325.000000,5.580000,23.470000,21886.000000,...,73.308000,24.471000,1.092000,7.530000,3.722000,2.190000,7.599000,29.300000,9637.860375,18.219357

#### 3.1 Missing values

In [4]:
from data_cleansing.manage_missing import replace_missing_values
Dataset_cleaned = replace_missing_values(workflow, Dataset)
print("Missing values after fill:")
print(Dataset_cleaned.isna().sum())

2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - ▶ Executing Workflow Step: 'replace_missing_values'

Missing values after fill:
Operator               0
SSE                    0
Mission                0
Seg                    0
Flight_segment         0
Type_segment           0
FLAP                   0
Altitude               0
TAS                    0
Time                   0
Distance               0
Pressure             508
THRUST               404
Mass                   0
ZFW                    0
PL                     0
FW                     0
1g                     0
Vertical maneuver      0
Vertical gust          0
Turn                   0
Frontal gust           0
n0                     0
Giro                   0
Xcg(%CMA)              0
Op-Mission             0
q                      0
gamma                  0
Mission_type           0
dtype: int64

#### 3.2 Outliers / Type_segment filter

In [5]:
from data_cleansing.manage_outliers import filter_outliers
Dataset_cleaned = filter_outliers(workflow, Dataset_cleaned)
print(f"Final shape: {Dataset_cleaned.shape}")
Dataset_cleaned.describe()

2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - ▶ Executing Workflow Step: 'filter_outliers'

After filtering 'Type_segment': 869 rows
Final shape: (869, 29)

,SSE,Seg,FLAP,Altitude,TAS,Time,Distance,Pressure,THRUST,Mass,...,1g,Vertical maneuver,Vertical gust,Turn,Frontal gust,n0,Giro,Xcg(%CMA),q,gamma
count,869.0,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000,361.000000,465.000000,869.000000,...,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000
mean,2110017.0,42.211738,2.218642,9294.634062,190.871043,5.671646,18.736686,3.170886,7.148645,18874.777906,...,53.622806,19.137703,0.649379,6.362113,0.480557,1.939056,1.995853,19.410690,4510.245290,-0.266692
std,0.0,28.767722,5.369574,7701.901926,48.867640,24.658221,90.687607,1.906679,6.800328,1324.688731,...,8.296235,2.454225,0.168054,0.641480,1.154103,0.077678,1.532889,4.094625,1845.316550,4.573436
min,2110017.0,7.000000,0.000000,18.000000,101.000000,0.100000,0.200000,0.130000,-3.250000,14125.000000,...,31.561000,12.031000,0.346600,4.122000,0.000000,1.730000,0.662000,14.600000,1652.386607,-39.450765
25%,2110017.0,18.000000,0.000000,2000.000000,144.000000,0.490000,1.600000,1.430000,-0.060000,17761.000000,...,47.364000,17.185000,0.509700,6.010000,0.000000,1.900000,1.299000,16.430000,2881.202593,-4.704237
50%,2110017.0,35.000000,0.000000,8000.000000,197.571208,0.930000,2.500000,3.440000,7.320000,18905.000000,...,51.778000,18.893000,0.575000,6.382000,0.000000,1.940000,1.587000,18.500000,3579.988216,0.000000
75%,2110017.0,60.000000,0.000000,15000.000000,230.000000,3.000000,9.600000,4.980000,11.970000,19991.000000,...,61.558000,21.394000,0.806000,6.830000,0.000000,1.980000,1.874000,20.580000,6375.463109,2.944179
max,2110017.0,122.000000,23.000000,26000.000000,302.000000,623.000000,2325.000000,5.580000,23.470000,21886.000000,...,73.308000,24.471000,1.092000,7.530000,3.722000,2.190000,7.599000,29.300000,9637.860375,18.219357

### Save

In [6]:
outputFilename = workflow.config['job_name'] + '_Dataset_cleaned.csv'
workflow.save_data(Dataset_cleaned, outputFilename)
workflow.save_metadata()

2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - File '/Users/martaarnabatmartin/Desktop/Pipelines/UCFatigue/pipeline/data/UCFATIGUE_1_Dataset_cleaned.csv' already exists — skipping save (delete data/ folder to rerun from scratch)

2026-06-25 12:24:22 - SurrogateFactoryLogs - INFO - Successfully saved workflow metadata to: /Users/martaarnabatmartin/Desktop/Pipelines/UCFatigue/pipeline/data/artifacts/metadata_UCFATIGUE_1.json